name: Waka Readme

on:
  schedule:
    # Runs every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: pt-BR
          SHOW_TOTAL_CODE_TIME: false
          SHOW_LINES_OF_CODE: true
          SHOW_UPDATED_DATE: true
          SHOW_LOC_CHART: false
